### ISSUE TITLE
Script crashes after picture

### ISSUE THREAD

**Issue by Me321** [guoarthur/Kijiji-Repost-Headless#3]
Here is a screenshot of the problem I get
![error](https://cloud.githubusercontent.com/assets/25507542/22552898/c02bd864-e928-11e6-8dca-838730df1ee9.png)

There seems to have a problem with the tmp dumb

How could I fix this ?

Thank you very much !

**Comment by Me321** [comment]
Fixed it by sending 2 pictures instead of one. Probably needed the , after the name of picture1.jpg to make it valid, that might be why it didn't work

**Comment by guoarthur** [comment]
Looking at the stacktrace you provided, it appears that the error is related to uploading the ad and not the  images. I tried to upload one of my test ads with 1 image, and I can't reproduce the bug. Could you send me your myAd.inf file that you're using? There shouldn't be any credentials in that file.

**Comment by Me321** [comment]
Thank you very much for your answer ! Here is the the .inf file ! I also tried using it without \n or é à and other special characters, but this led to the same errors as you can see in the screenshot.

**Comment by Me321** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/25507542/22751970/a937945a-ee04-11e6-851a-212ab880f242.png)

It also appears that the problem comes from after the picture uploading part. Maybe it's something that is specific to the real estate category that might miss ?

**Comment by jackm** [comment]
The error you are seeing is actually telling you that it wasn't able to open (and create) the file '/tmp/kijiji-api-dump' which makes sense since on a Windows platform this file path doesn't exist.

The actual problem was that something earlier in the program failed and raised a "PostAdException" from within the "postAdUsingData" function [on this line](https://github.com/guoarthur/Kijiji-Repost-Headless/blob/master/KijijiApi.py#L146). The condition when this exception gets raised is that either the HTTP status code was not 200 (meaning it did not return "OK"), _or_ it did not find the text string "message-container success" within the response text. Unfortunately because it wasn't able to open the debug log file to write to, you don't have any further details to look at.

I suggest changing the init function within KijijiApiException [here](https://github.com/guoarthur/Kijiji-Repost-Headless/blob/master/KijijiApi.py#L12) so that when an exception is raised, it has a proper place to write the debug output to. Then you can figure out what really went wrong.
